<html>
<head><title>Pansophy Contact Manager - Student Affairs</title></head>
<!--[if !IE]><!-->
	
<FRAMESET ROWS="96,*,50" BORDERCOLOR="000000" FRAMESPACING="0" BORDER="0" style="padding:0;margin:0;">
<!--<![endif]-->
<!--[if IE]>

<FRAMESET ROWS="100,*,50" BORDERCOLOR="000000" FRAMESPACING="0" BORDER="0" >

<![endif]-->
<FRAME NAME="Menu" TARGET="Main" src="./menu.php?table=students" NORESIZE SCROLLING="NO" frameborder="0" style="border: thick solid #000000;margin:-3%;padding:0;" >
<FRAME NAME="Main" src="./main.php" NORESIZE frameborder="0">
<FRAME NAME="AlertBox" src="./alert.php" NORESIZE SCROLLING="NO" frameborder="0">
<NOFRAMES>
<body bgcolor = "FFFFFF">
This software will not work with a browser that does not have frames enabled.  Please
get one from <a href="http://www.mozilla.org">The Mozilla Group.</a>
</body>
</NOFRAMES>
</FRAMESET>
</html>
