<html>
<head>
<title>Phronesis Contact Manager - Student Affairs</title>
<!--this is the header that's included on (most) every page.
it pretty much just defines the stylesheets.  the awesome part is that
because this file is being included in all the main files and all the
interface/ files, site(print).css has to be both in the main directory and the
interface/ directory-->
<!--[if !IE]><!-->
	<link rel="stylesheet" type="text/css" href="site.css" />
<!--<![endif]-->

<!--[if IE]>

	<link rel="stylesheet" type="text/css" href="siteie.css" />

<![endif]-->

<!-- 
	<link rel="stylesheet" type="text/css" href="siteprint.css" />
 -->
</head>
<body style="margin:0;">

