<?php

/**
 * Page allows user to create a report on interims.
 */

//+-----------------------------------------------------------------------------------------+

include( "../DataAccessManager.inc.php" );
//include( "../include/MyDate.inc.php" );
include( "../include/header.inc" );
include( '../include/miscfunctions.inc.php' );
$dam = new DataAccessManager();

//+-----------------------------------------------------------------------------------------+

// this should be put in a seperate file
function urlGetLine() {
	$getline = "";
	$first = true;
	foreach( $_GET as $attribute => $value ) {
		if( !$first ) $getline .= "&";
		$getline .= $attribute."=".urlencode( $value );
		$first = false;
	}
	if( !$first ) $getline = "?".$getline;
	return $getline;
}

$reportName = $dam->getReportNameForSelf( 'interim', urlGetLine() );

/////////////////////
//
//  form information
//
/////////////////////
$startdatelabel = "Start date:";
$startdatename = "start";

$enddatelabel = "End date:";
$enddatename = "end";

$submitbuttonname = "submit";
$submitbuttonvalue = "Generate Report";
/////////////////////
//
//  end form information
//
/////////////////////


function printPage() {
	global $dam, $startdatelabel, $startdatename, $enddatelabel, $enddatename, $submitbuttonname, $submitbuttonvalue;
	
   //start page
	echo "<center><h2>Interim Report</h2>";
	echo "<form><table class='greybg'  cellspacing='0' cellpadding='5'>";
		
	//print dates	
	if( isset($_GET[$startdatename]) ) $startdatevalue = getShortDate( $_GET[$startdatename] );
	if( isset($_GET[$enddatename]) ) $enddatevalue = getShortDate( $_GET[$enddatename] );
	echo "<tr>
			 <th class='darkbg' valign='top' align='right'>
			 	 $startdatelabel
			 </th>
			 <td valign='top' align='left'>
			 	<input type='text' name='$startdatename' value='$startdatevalue'>
			 </td>
		  </tr>
		  <tr>
		 	 <th class='darkbg' valign='top' align='right'>
				 $enddatelabel
			 </th>
			 <td valign='top' align='left'>
				 <input type='text' name='$enddatename' value='$enddatevalue'>
			 </td>
		  </tr>";
		
	//print submit button	
	echo "<tr>
			  <td class='colorbg' colspan='2' valign='top' align='center'>
			  	  <input type='submit' name='$submitbuttonname' value='$submitbuttonvalue'>
			  </td>
		  </tr>";
		  
	//end of page	  
	echo "</form></table>";
	echo "</center>";
}


function getShortDate( $date ) {
	$date = new MyDate( $date );
	return $date->humanDateNumerical();
}

function getMySqlDate( $date ) {
	$date = new MyDate( $date );
	return $date->mySqlDate();
}

function readableDateTime( $mysql_datetime ) {
	$datetime = new MyDate( $mysql_datetime );
	$date = $datetime->humanDateNumerical();
	$time = $datetime->humanTime12Hour();
	return $date." at ".$time;
}



/**
 * Calls dam function to process an interim report
 *
 * @return interim report
 */
function processInterimReport() {
	global $dam, $startdatename, $enddatename;
					     
	return $dam->getInterimReport( $_GET[$startdatename], $_GET[$enddatename] );
}

/**
 * Prints form to save an interim report
 */
function printSaveInterimReportForm() {
	global $dam;
	echo '<center><p class="largecolorheading">New Interim Report</p>
		  </center>';
	
	echo "<center>
	<form method='post' action='".basename( $SELF ).urlGetLine()."'>
		<table  cellpadding='5' cellspacing='0'>
		<tr>
			<th class='darkbg'>Report name:
			</th>
			<td class='greybg'><input type='text' size='40%' name='reportname' value='".$_POST['reportname']."'>
			</td>
		</tr>
		<tr>
			<td align='center' colspan='2'><input type='submit' name='savereport' value='Save this Report'>
			</td>
		</tr>
		</table>
	<input type='hidden' name='getline' value='".urlGetLine()."'>
	</form>
	</center>";
}

/**
 * Prints an interim report's name
 */
function printInterimReportName() {
	global $reportName;
	echo "
	<h2>Interim Report: $reportName</h2>
	<center>This report is saved. <a href='deletereport.php?type=interim&name=".urlencode($reportName)."'>[Delete]</a></center><br>
	";
}

/**
 * Prints an interim report
 *
 * @param $report interim report generated by processInterimReport()
 */
function printInterimReport( $report ) {
	global $dam;

	echo "<center>
	<table width='80%' class='report'>";
	for($i = 0; $i < count($report); $i++){
      $interim = $report[$i];
      $student = $dam->viewStudent('',$interim['studentid']);
      if($dam->userCanViewInterim('')){
         echo '<tr><td>';
         echo 'Interim: <a href="./viewinterim.php?id='.$interim['interimid'].'">'.$interim['interimid'].'</a><br>';
         echo '<a href="./viewstudent.php?id='.$interim['studentid'].'">'.$student['LAST_NAME'].', '.$student['FIRST_NAME'].' '.$student['MIDDLE_NAME'].'</a><br>';
         echo 'Course: '.$interim['course'].'<br>';
         echo 'Date Processed: '.getShortDate($interim['dateprocessed']);         
         echo '</td></tr>';
      }
   }
	echo "</table></center>";
}




if( isset($_POST['savereport']) && isset($_POST['reportname'] )) {
	$dam->saveReportForSelf( 'interim', $_POST['reportname'], $_POST['getline'] );
	$reportName = $dam->getReportNameForSelf( 'interim', urlGetLine() );
	if( $reportName ) printInterimReportName();
	else printSaveInterimReportForm();
	printInterimReport( processInterimReport() );
}
else if( isset($_GET[$submitbuttonname]) ) {
	if( $reportName ) printInterimReportName();
	else printSaveInterimReportForm();
	printInterimReport( processInterimReport() );
}
else printPage();


?>
